### ISSUE TITLE
Won't build with statistics v0.14.X.X

### ISSUE THREAD

**Issue by masterdezign** [alpmestan/probable#4]
> Preprocessing library probable-0.1.2...
> [1 of 4] Compiling Math.Probable.Random ( src/Math/Probable/Random.hs, dist/build/Math/Probable/Random.o )
> [2 of 4] Compiling Math.Probable.Distribution.Finite ( src/Math/Probable/Distribution/Finite.hs, dist/build/Math/Probable/Distribution/Finite.o )
> [3 of 4] Compiling Math.Probable.Distribution ( src/Math/Probable/Distribution.hs, dist/build/Math/Probable/Distribution.o )
> src/Math/Probable/Distribution.hs:249:33: error:
>     Not in scope: ‘N.normalFromSample’
>     Module ‘Statistics.Distribution.Normal’ does not export ‘normalFromSample’.
> src/Math/Probable/Distribution.hs:273:38: error:
>     Not in scope: ‘E.exponentialFromSample’
>     Module ‘Statistics.Distribution.Exponential’ does not export ‘exponentialFromSample’.
> cabal: Leaving directory '/tmp/cabal-tmp-10404/probable-0.1.2'
> cabal: Error: some packages failed to install:
> probable-0.1.2 failed during the building phase. The exception was:
> ExitFailure 1
>

**Comment by masterdezign** [comment]
The easiest thing to do is to restrict `statistics >= 0.10 && < 0.14` in .cabal file.

**Comment by alpmestan** [comment]
@masterdezign I made that exact change on hackage directly, as you can now see at https://hackage.haskell.org/package/probable-0.1.2 -- let me know if that fixes it.

If anyone submits a PR to work with the latest version of `statistics` I'd definitely take it. Don't have quite the time to figure out what has changed these days, but can take a look in the upcoming month.

**Comment by alpmestan** [comment]
0.1.3 has been released some time ago and it supports `statistics >= 0.14`. Closing this issue, please do reopen if there's a problem.
